<?php

/**
 * BaseExtractionLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $extraction_driver
 * @property timestamp $started_on
 * @property timestamp $finished_on
 * @property int $resources_parsed
 * @property int $urls_extracted
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method string        getExtractionDriver()  Returns the current record's "extraction_driver" value
 * @method timestamp     getStartedOn()         Returns the current record's "started_on" value
 * @method timestamp     getFinishedOn()        Returns the current record's "finished_on" value
 * @method int           getResourcesParsed()   Returns the current record's "resources_parsed" value
 * @method int           getUrlsExtracted()     Returns the current record's "urls_extracted" value
 * @method ExtractionLog setId()                Sets the current record's "id" value
 * @method ExtractionLog setExtractionDriver()  Sets the current record's "extraction_driver" value
 * @method ExtractionLog setStartedOn()         Sets the current record's "started_on" value
 * @method ExtractionLog setFinishedOn()        Sets the current record's "finished_on" value
 * @method ExtractionLog setResourcesParsed()   Sets the current record's "resources_parsed" value
 * @method ExtractionLog setUrlsExtracted()     Sets the current record's "urls_extracted" value
 * 
 * @package    vanilla-miner
 * @subpackage model
 * @author     Constructions Incongrues
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtractionLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extraction_log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('extraction_driver', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('started_on', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finished_on', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('resources_parsed', 'int', null, array(
             'type' => 'int',
             'default' => 0,
             ));
        $this->hasColumn('urls_extracted', 'int', null, array(
             'type' => 'int',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}