<?php

/**
 * ExtractionLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vanilla-miner
 * @subpackage model
 * @author     Constructions Incongrues
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExtractionLog extends BaseExtractionLog
{
}
