<?php

/**
 * Link
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vanilla-miner
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{
  /**
   * Automatically populates link's attributes based on URL analysis.
   * 
   * @throws InvalidArgumentException if link's "url" attribute is not set
   */
  public function autoPopulate(array $extensions_mimetype_map = array())
  {
    // Analyze URL
    $url_components = parse_url($this->url);
    if (!$url_components)
    {
      throw new InvalidArgumentException(sprintf('"%s" is not a valid URL', $this->url));      
    }
    
    // Set domain information
    $this->domain_fqdn = $url_components['host'];
    $domain_parts = array_reverse(explode('.', $url_components['host']));
    if (count($domain_parts) > 2)
    {
      $this->domain_parent = sprintf('%s.%s', $domain_parts[1], $domain_parts[0]);
    }
    
    // Try to guess document mimetype from extension
    if (isset($url_components['path']))
    {
      $document_extension = pathinfo($url_components['path'], PATHINFO_EXTENSION);
      if (isset($extensions_mimetype_map[$document_extension]))
      {
        $mimetype = $extensions_mimetype_map[$document_extension];
        $this->mime_type = $mimetype;
      }
    }
  }
}
