# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Returns segment data depending on query parameters and required response format
resources_collection_segment_get:
  url:    /collections/:collection/segments/:segment/get
  param: { module: resource, action: get, sf_format: html }

# Shows available response formats for required resource segment
resources_collection_segment_formats:
  url:    /collections/:collection/segments/:segment/formats
  param: { module: resource, action: formats }

# Shows available segments for required resource collection
resources_collection_segments:
  url:    /collections/:collection/segments
  param: { module: resource, action: segments }

# Shows documentation and drill down links for required resource collection
resources_collection:
  url:    /collections/:collection
  param: { module: resource, action: segments }

# Lists all available resources
resources:
  url:    /collections
  param: { module: resource, action: collections }

# Homepage
homepage:
  url:    /
  param: { module: resource, action: collections }
