# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Returns segment data depending on query parameters and required response format
resources_type_segment_get:
  url:    /resources/:type/segments/:segment/get
  param: { module: resource, action: get, sf_format: html }

# Shows available resource types for required resource type
resources_type_segment_formats:
  url:    /resources/:type/segments/:segment/formats
  param: { module: resource, action: formats }

# Shows available segments for required resource type
resources_type_segments:
  url:    /resources/:type/segments
  param: { module: resource, action: segments }

# Shows documentation and drill down links for required resource type
resources_type:
  url:    /resources/:type
  param: { module: resource, action: segments }

# Lists all available resources
resources:
  url:    /resources
  param: { module: resource, action: types }

# Homepage
homepage:
  url:    /
  param: { module: resource, action: types }
