# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        "Musiques Incongrues : DATA !" 
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    ["http://fonts.googleapis.com/css?family=Crimson+Text", "http://fonts.googleapis.com/css?family=Lobster", "main.css?v=1"]

  javascripts:    ["http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "jquery.slug.js", "behaviors.js?v=5"]

  has_layout:     true
  layout:         layout
