<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('extraction_log', 'resources_parsed', 'int', '', array(
             ));
        $this->addColumn('extraction_log', 'urls_extracted', 'int', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('extraction_log', 'resources_parsed');
        $this->removeColumn('extraction_log', 'urls_extracted');
    }
}