<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('extraction_log', 'resources_parsed', 'int', '', array(
             'default' => '0',
             ));
        $this->changeColumn('extraction_log', 'urls_extracted', 'int', '', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}