<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('extraction_log', 'duration');
        $this->addColumn('extraction_log', 'started_on', 'timestamp', '25', array(
             ));
        $this->addColumn('extraction_log', 'finished_on', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->addColumn('extraction_log', 'duration', 'int', '', array(
             ));
        $this->removeColumn('extraction_log', 'started_on');
        $this->removeColumn('extraction_log', 'finished_on');
    }
}