<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('extraction_log', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => '1',
              'primary' => '1',
              'length' => '8',
             ),
             'extraction_driver' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'duration' => 
             array(
              'type' => 'int',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('extraction_log');
    }
}