Link:
  actAs:
    Timestampable:
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
      notnull: true
    url:
      type:    string
      notnull: true
    domain_parent:
      type:    string
      notnull: true
    domain_fqdn:
      type:    string
      notnull: true    
    mime_type: 
      type:    string
    contributed_at:
      # Makes it easier to comply with solr date format
      type:    string 
    contributor_id:
      type:    integer
    contributor_name:
      type:    string
    comment_id:
      type:    integer
    discussion_id:
      type:    integer
    discussion_name:
      type:    string
    is_available:
      type:    boolean
    expanded_at:
      type:    timestamp
  indexes:
    idx_url:
      fields:
        url:
          length: 512
      type:   unique
    idx_expanded_at:
      fields: [expanded_at]
    idx_is_available:
      fields: [is_available]